appname: task3

logging:
  version: 1
  formatters:
    short:
      format: '%(levelname)s: %(message)s'
    long:
      format: '[%(asctime)s] %(levelname)s @line-%(lineno)d: %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: long
      level: DEBUG
  root:
    level: DEBUG
    handlers: [console]

inputs:
  tech: hdfs://127.0.0.1:9000/user/iignatov/data/emp_tech.csv
  salary: hdfs://127.0.0.1:9000/user/iignatov/data/emp_salary.csv

outputs:
  joined: hdfs://127.0.0.1:9000/user/iignatov/data/output/task3/joined
  