appname: task5

logging:
  version: 1
  formatters:
    short:
      format: '%(levelname)s: %(message)s'
    long:
      format: '[%(asctime)s] %(levelname)s @line-%(lineno)d: %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: long
      level: DEBUG
  root:
    level: DEBUG
    handlers: [ console ]

inputs:
  products: hdfs://127.0.0.1:9000/user/training/pyspark/tasks/products.csv
  sales: hdfs://127.0.0.1:9000/user/training/pyspark/tasks/sales.csv
  sellers: hdfs://127.0.0.1:9000/user/training/pyspark/tasks/sellers.csv

outputs:
  statistics: hdfs://127.0.0.1:9000/user/iignatov/data/output/task5/statistics
  unique_products: hdfs://127.0.0.1:9000/user/iignatov/data/output/task5/prod_count_by_date
  sales: hdfs://127.0.0.1:9000/user/iignatov/data/output/task5/sales
  