appname: task2

logging:
  version: 1
  formatters:
    short:
      format: '%(levelname)s: %(message)s'
    long:
      format: '[%(asctime)s] %(levelname)s @line-%(lineno)d: %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: long
      level: DEBUG
  root:
    level: DEBUG
    handlers: [console]

inputs:
  tech_inc: hdfs://127.0.0.1:9000/user/iignatov/data/Tech_Inc.txt
  mptech: hdfs://127.0.0.1:9000/user/iignatov/data/MPTech.txt

outputs:
  merged: hdfs://127.0.0.1:9000/user/iignatov/data/output/task2/MergedData
  tech_inc: hdfs://127.0.0.1:9000/user/iignatov/data/output/task2/Tech_Inc
  mptech: hdfs://127.0.0.1:9000/user/iignatov/data/output/task2/MPTech
  